name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Push to registry
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          username: sironheart
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sironheart/blog

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            TORCHLIGHT_TOKEN=${{ secrets.TORCHLIGHT_TOKEN }}
