name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Push to registry
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: s1ronheart/nginx-blog
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          TORCHLIGHT_TOKEN=${{ secrets.TORCHLIGHT_TOKEN }}
